#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

upstream_version=$(ynh_read_manifest "version" | cut -d'~' -f1)
mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

pushd "$install_dir"
 python3 -m venv venv
 venv/bin/pip install --upgrade pip setuptools wheel
 venv/bin/pip install open-webui=="$upstream_version"
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"
mkdir -p "/var/log/$app"
chown "$app:$app" "/var/log/$app"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_systemctl --service="$app" --action="start" --wait_until="Application startup complete." --timeout=600

yunohost service add "$app" --description="User-friendly AI Interface (Supports Ollama, OpenAI API, ...)" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
